package com.example.data

data class MemoryItem(
    val id: String,
    val title: String,
    val date: String,
    val note: String,
    val iconType: String = "heart" // "heart", "tree", "flower", "cooking", "stars", "couch"
)

data class LoveNoteItem(
    val id: String,
    val text: String,
    val author: String,
    val date: String,
    val isCustom: Boolean = false
)

data class TinyMoment(
    val dayIndex: Int,
    val title: String,
    val description: String,
    val sceneHint: String,
    val quote: String
)

/** A Polaroid-style captured memory from the heart button. */
data class PolaroidMemory(
    val id: String,
    val title: String,        // Cozy autogenerated title
    val date: String,         // e.g. "Sep 28, 2026"
    val time: String,         // e.g. "10:49 PM"
    val sceneName: String,    // e.g. "Lantern Stroll"
    val sceneEnvKey: String,  // e.g. "PATH_NIGHT"
    val imagePath: String     // Absolute path to PNG file in internal storage
)

/** A Shared Dream Journal entry — keyword-matched visual dream state. */
data class DreamEntry(
    val id: String,
    val text: String,                   // Raw typed dream phrase
    val matchedKeywords: List<String>,  // Keywords matched from the phrase
    val dreamTheme: String,             // Canonical theme name e.g. "JAPAN", "NORWAY", "FALLBACK"
    val timestamp: Long                 // System.currentTimeMillis()
)

/** Active temporary Dream Mode state — exists only while visualizing a dream. */
data class DreamState(
    val theme: String,
    val text: String,
    val alpha: Float = 1.0f
)

/** Seasonal artifacts for couple's home table / mantelpiece. */
enum class SeasonalArtifact {
    SPRING_BLOSSOM_VASE,
    SUMMER_ICED_CARAFE,
    AUTUMN_HARVEST_PUMPKIN,
    WINTER_WARM_COCOA
}

/**
 * Organic Tiny Home Evolution state:
 * Gradual introduction of objects, plants, photos, and artifacts
 * based on days together, keepsakes, and memories without levels or XP.
 */
data class HomeEvolutionState(
    val hasWindowsillPlant: Boolean = false,
    val hasCozyKnitThrow: Boolean = false,
    val hasCopperTeakettle: Boolean = false,
    val hasCornerMonstera: Boolean = false,
    val hasFairyStringLights: Boolean = false,
    val hasHangingMacrame: Boolean = false,
    val hasFramedKeepsake: Boolean = false,
    val hasFridgePolaroid: Boolean = false,
    val hasFridgeLoveNote: Boolean = false,
    val hasAdventurePicnicBasket: Boolean = false,
    val hasBedsideNotepad: Boolean = false,
    val hasMiniGameBoard: Boolean = false,
    val hasOrigamiHeart: Boolean = false,
    val seasonalArtifact: SeasonalArtifact = SeasonalArtifact.SPRING_BLOSSOM_VASE
)

