package com.example.data

import android.content.ContentValues
import android.content.Context
import android.content.SharedPreferences
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color as AndroidColor
import android.graphics.Paint
import android.graphics.Rect
import android.graphics.RectF
import android.graphics.Typeface
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import java.io.File
import java.io.FileOutputStream
import java.util.UUID
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.graphics.asImageBitmap
import com.example.ui.PolaroidPhotos

/**
 * Captures and keeps Polaroid memories on Android (heart button feature): the card images in the
 * app's files, the photo library export, and the card drawing. The list, titles and dates are the
 * shared [PolaroidStore] (SharedPreferences "tiny_us_polaroids").
 */
class PolaroidManager(private val context: Context) : PolaroidPhotos {

    private val prefs: SharedPreferences =
        context.getSharedPreferences("tiny_us_polaroids", Context.MODE_PRIVATE)
    private val store = PolaroidStore(SharedPreferencesStorage(prefs), ::deleteImage)

    // ─── Image I/O & Card Rendering ───────────────────────────────────────────

    /**
     * Saves [bitmap] as a lossless PNG into internal storage.
     * Returns the absolute path of the saved file.
     */
    fun saveBitmap(bitmap: Bitmap): String {
        val dir = File(context.filesDir, "polaroids").also { it.mkdirs() }
        val file = File(dir, "pol_${System.currentTimeMillis()}_${UUID.randomUUID().toString().take(6)}.png")
        FileOutputStream(file).use { out ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
        }
        return file.absolutePath
    }

    /**
     * Loads the bitmap from an absolute [path]. Returns null if the file is missing or unreadable.
     */
    fun loadBitmap(path: String): Bitmap? = runCatching {
        android.graphics.BitmapFactory.decodeFile(path)
    }.getOrNull()

    /**
     * Loads the Polaroid card for [memory]. If the stored file is a legacy raw screenshot,
     * automatically converts it into a complete Polaroid card and updates disk.
     */
    fun loadPolaroidBitmap(memory: PolaroidMemory): Bitmap? {
        val raw = loadBitmap(memory.imagePath) ?: return null
        if (raw.height.toFloat() / raw.width.toFloat() > 1.7f) {
            val rendered = renderPolaroidCard(
                sceneBitmap = raw,
                title = memory.title,
                date = memory.date,
                time = memory.time,
                sceneName = memory.sceneName
            )
            runCatching {
                FileOutputStream(File(memory.imagePath)).use { out ->
                    rendered.compress(Bitmap.CompressFormat.PNG, 100, out)
                }
            }
            return rendered
        }
        return raw
    }

    /**
     * Renders a complete, authentic Polaroid instant film photograph:
     * - Warm soft-white instant-film frame with rounded corners and subtle border
     * - Cropped scene photograph centered on the couple (status bar & system HUD excluded)
     * - Inner photo border
     * - Autogenerated title in bold warm serif typography
     * - Scene name & date line
     * - Timestamp
     * - Cozy "TINY US" watermark with a small pixel-art heart
     *
     * Dimensions: 1080 x 1440 px (classic 3:4 photo print proportions).
     */
    fun renderPolaroidCard(
        sceneBitmap: Bitmap,
        title: String,
        date: String,
        time: String,
        sceneName: String
    ): Bitmap {
        val cardWidth = 1080
        val cardHeight = 1440
        val cardBitmap = Bitmap.createBitmap(cardWidth, cardHeight, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(cardBitmap)

        // 1. Warm Instant-Film Paper Background
        val paperPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#FAF8F5")
            style = Paint.Style.FILL
        }
        val cardRect = RectF(0f, 0f, cardWidth.toFloat(), cardHeight.toFloat())
        val cornerRadius = 24f
        canvas.drawRoundRect(cardRect, cornerRadius, cornerRadius, paperPaint)

        // 2. Photo Area: 960 x 980 px (Top: 60, Left: 60, Right: 1020, Bottom: 1040)
        val photoLeft = 60f
        val photoTop = 60f
        val photoRight = 1020f
        val photoBottom = 1040f
        val targetPhotoWidth = photoRight - photoLeft   // 960f
        val targetPhotoHeight = photoBottom - photoTop  // 980f

        // Photo background (dark slate back)
        val photoBgPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#1A1A1A")
            style = Paint.Style.FILL
        }
        canvas.drawRect(photoLeft, photoTop, photoRight, photoBottom, photoBgPaint)

        // Crop scene bitmap centered on the characters (excluding top status bar & bottom HUD)
        val sw = sceneBitmap.width
        val sh = sceneBitmap.height
        val targetRatio = targetPhotoWidth / targetPhotoHeight
        val srcRatio = sw.toFloat() / sh.toFloat()

        val srcRect = if (srcRatio > targetRatio) {
            val cropW = (sh * targetRatio).toInt().coerceAtMost(sw)
            val srcX = (sw - cropW) / 2
            Rect(srcX, 0, srcX + cropW, sh)
        } else {
            val cropH = (sw / targetRatio).toInt().coerceAtMost(sh)
            val srcY = ((sh - cropH) * 0.48f).toInt().coerceIn(0, (sh - cropH).coerceAtLeast(0))
            Rect(0, srcY, sw, srcY + cropH)
        }

        val dstRect = RectF(photoLeft, photoTop, photoRight, photoBottom)
        val photoPaint = Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG)
        canvas.drawBitmap(sceneBitmap, srcRect, dstRect, photoPaint)

        // Inner photo frame border (subtle 1.5px bevel)
        val photoBorderPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#DDD7CE")
            style = Paint.Style.STROKE
            strokeWidth = 2f
        }
        canvas.drawRect(photoLeft, photoTop, photoRight, photoBottom, photoBorderPaint)

        // 3. Caption Area (y = 1040 to 1440)
        // Autogenerated Title — Bold serif typeface
        val titlePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#1E293B")
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            textAlign = Paint.Align.CENTER
            textSize = 48f
        }
        // Auto-scale title down if it's too long
        while (titlePaint.measureText(title) > (cardWidth - 140f) && titlePaint.textSize > 30f) {
            titlePaint.textSize -= 2f
        }
        canvas.drawText(title, cardWidth / 2f, 1145f, titlePaint)

        // Scene Name & Date Line — Soft serif
        val datePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#64748B")
            typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
            textSize = 28f
        }
        val dateText = if (sceneName.isNotBlank() && date.isNotBlank()) {
            "$sceneName  •  $date"
        } else {
            sceneName.ifBlank { date }
        }
        canvas.drawText(dateText, cardWidth / 2f, 1215f, datePaint)

        // Timestamp Line — Clean monospace
        if (time.isNotBlank()) {
            val timePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
                color = AndroidColor.parseColor("#94A3B8")
                typeface = Typeface.MONOSPACE
                textAlign = Paint.Align.CENTER
                textSize = 22f
            }
            canvas.drawText(time, cardWidth / 2f, 1270f, timePaint)
        }

        // Tiny Us cozy brand mark at the bottom
        val brandPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#E5989B")
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
            textSize = 20f
            letterSpacing = 0.14f
        }
        val brandText = "T I N Y   U S"
        val brandWidth = brandPaint.measureText(brandText)
        // Heart + gap + text are centred together; the heart is drawn as pixel art, not a glyph.
        val cell = 3f
        val heartWidth = 7 * cell
        val gap = 14f
        val startX = cardWidth / 2f - (heartWidth + gap + brandWidth) / 2f
        val heartPaint = Paint().apply { color = brandPaint.color; style = Paint.Style.FILL }
        val heartTop = 1370f - 17f
        PIXEL_HEART.forEachIndexed { row, line ->
            line.forEachIndexed { col, c ->
                if (c == 'X') {
                    val x = startX + col * cell
                    val y = heartTop + row * cell
                    canvas.drawRect(x, y, x + cell, y + cell, heartPaint)
                }
            }
        }
        brandPaint.textAlign = Paint.Align.LEFT
        canvas.drawText(brandText, startX + heartWidth + gap, 1370f, brandPaint)

        // Outer card border
        val cardBorderPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#E8E2D8")
            style = Paint.Style.STROKE
            strokeWidth = 2f
        }
        canvas.drawRoundRect(
            RectF(1f, 1f, cardWidth - 1f, cardHeight - 1f),
            cornerRadius,
            cornerRadius,
            cardBorderPaint
        )

        return cardBitmap
    }

    /**
     * Saves the complete Polaroid card [bitmap] into the device's public Pictures/Tiny Us gallery.
     * Accessible immediately from Google Photos and Device Gallery.
     * Returns true on success, false on error.
     */
    fun saveToDeviceGallery(bitmap: Bitmap, title: String): Boolean {
        return runCatching {
            val cleanTitle = title.replace(Regex("[^a-zA-Z0-9]"), "_").take(20)
            val filename = "TinyUs_${cleanTitle}_${System.currentTimeMillis()}.png"
            val resolver = context.contentResolver

            val values = ContentValues().apply {
                put(MediaStore.Images.Media.DISPLAY_NAME, filename)
                put(MediaStore.Images.Media.MIME_TYPE, "image/png")
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    put(MediaStore.Images.Media.RELATIVE_PATH, Environment.DIRECTORY_PICTURES + File.separator + "Tiny Us")
                    put(MediaStore.Images.Media.IS_PENDING, 1)
                }
            }

            val uri = resolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values)
                ?: return false

            resolver.openOutputStream(uri)?.use { out ->
                bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
            } ?: return false

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                values.clear()
                values.put(MediaStore.Images.Media.IS_PENDING, 0)
                resolver.update(uri, values, null, null)
            }
            true
        }.getOrDefault(false)
    }

    /**
     * Deletes the image file at [path]. No-op if already absent.
     */
    fun deleteImage(path: String) {
        File(path).takeIf { it.exists() }?.delete()
    }

    // ─── Shared screens (PolaroidPhotos) ──────────────────────────────────────

    override fun loadCard(memory: PolaroidMemory): ImageBitmap? = loadPolaroidBitmap(memory)?.asImageBitmap()

    override fun saveToGallery(card: ImageBitmap, title: String): Boolean = saveToDeviceGallery(card.asAndroidBitmap(), title)

    override fun loadThumbnail(path: String, maxWidth: Int): ImageBitmap? = runCatching {
        val bounds = android.graphics.BitmapFactory.Options().apply { inJustDecodeBounds = true }
        android.graphics.BitmapFactory.decodeFile(path, bounds)
        var sample = 1
        while (bounds.outWidth / (sample * 2) >= maxWidth) sample *= 2
        android.graphics.BitmapFactory.decodeFile(path, android.graphics.BitmapFactory.Options().apply { inSampleSize = sample })?.asImageBitmap()
    }.getOrNull()

    // ─── Metadata, titles and dates (shared PolaroidStore) ───────────────────

    override fun getPolaroids(): List<PolaroidMemory> = store.getPolaroids()

    fun savePolaroid(memory: PolaroidMemory) = store.savePolaroid(memory)

    override fun deletePolaroid(id: String) = store.deletePolaroid(id)

    fun pickTitle(sceneEnvKey: String, isNight: Boolean = false, isSunset: Boolean = false): String =
        store.pickTitle(sceneEnvKey, isNight, isSunset)

    fun formattedDate(): String = store.formattedDate()

    fun formattedTime(): String = store.formattedTime()

    companion object {
        /** 7x6 pixel heart for the watermark ('X' = filled cell). */
        private val PIXEL_HEART = listOf(
            ".XX.XX.",
            "XXXXXXX",
            "XXXXXXX",
            ".XXXXX.",
            "..XXX..",
            "...X..."
        )
    }
}
