package com.example.data

import android.content.ContentValues
import android.content.Context
import android.content.SharedPreferences
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color as AndroidColor
import android.graphics.Paint
import android.graphics.Rect
import android.graphics.RectF
import android.graphics.Typeface
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

/**
 * Manages capture and persistence of Polaroid memories (heart button feature).
 * All storage is local: images → internal files dir, metadata → SharedPreferences JSON.
 */
class PolaroidManager(private val context: Context) {

    private val prefs: SharedPreferences =
        context.getSharedPreferences("tiny_us_polaroids", Context.MODE_PRIVATE)

    // ─── Image I/O & Card Rendering ───────────────────────────────────────────

    /**
     * Saves [bitmap] as a lossless PNG into internal storage.
     * Returns the absolute path of the saved file.
     */
    fun saveBitmap(bitmap: Bitmap): String {
        val dir = File(context.filesDir, "polaroids").also { it.mkdirs() }
        val file = File(dir, "pol_${System.currentTimeMillis()}_${UUID.randomUUID().toString().take(6)}.png")
        FileOutputStream(file).use { out ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
        }
        return file.absolutePath
    }

    /**
     * Loads the bitmap from an absolute [path]. Returns null if the file is missing or unreadable.
     */
    fun loadBitmap(path: String): Bitmap? = runCatching {
        android.graphics.BitmapFactory.decodeFile(path)
    }.getOrNull()

    /**
     * Loads the Polaroid card for [memory]. If the stored file is a legacy raw screenshot,
     * automatically converts it into a complete Polaroid card and updates disk.
     */
    fun loadPolaroidBitmap(memory: PolaroidMemory): Bitmap? {
        val raw = loadBitmap(memory.imagePath) ?: return null
        if (raw.height.toFloat() / raw.width.toFloat() > 1.7f) {
            val rendered = renderPolaroidCard(
                sceneBitmap = raw,
                title = memory.title,
                date = memory.date,
                time = memory.time,
                sceneName = memory.sceneName
            )
            runCatching {
                FileOutputStream(File(memory.imagePath)).use { out ->
                    rendered.compress(Bitmap.CompressFormat.PNG, 100, out)
                }
            }
            return rendered
        }
        return raw
    }

    /**
     * Renders a complete, authentic Polaroid instant film photograph:
     * - Warm soft-white instant-film frame with rounded corners and subtle border
     * - Cropped scene photograph centered on the couple (status bar & system HUD excluded)
     * - Inner photo border
     * - Autogenerated title in bold warm serif typography
     * - Scene name & date line
     * - Timestamp
     * - Cozy "♥ TINY US" watermark
     *
     * Dimensions: 1080 x 1440 px (classic 3:4 photo print proportions).
     */
    fun renderPolaroidCard(
        sceneBitmap: Bitmap,
        title: String,
        date: String,
        time: String,
        sceneName: String
    ): Bitmap {
        val cardWidth = 1080
        val cardHeight = 1440
        val cardBitmap = Bitmap.createBitmap(cardWidth, cardHeight, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(cardBitmap)

        // 1. Warm Instant-Film Paper Background
        val paperPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#FAF8F5")
            style = Paint.Style.FILL
        }
        val cardRect = RectF(0f, 0f, cardWidth.toFloat(), cardHeight.toFloat())
        val cornerRadius = 24f
        canvas.drawRoundRect(cardRect, cornerRadius, cornerRadius, paperPaint)

        // 2. Photo Area: 960 x 980 px (Top: 60, Left: 60, Right: 1020, Bottom: 1040)
        val photoLeft = 60f
        val photoTop = 60f
        val photoRight = 1020f
        val photoBottom = 1040f
        val targetPhotoWidth = photoRight - photoLeft   // 960f
        val targetPhotoHeight = photoBottom - photoTop  // 980f

        // Photo background (dark slate back)
        val photoBgPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#1A1A1A")
            style = Paint.Style.FILL
        }
        canvas.drawRect(photoLeft, photoTop, photoRight, photoBottom, photoBgPaint)

        // Crop scene bitmap centered on the characters (excluding top status bar & bottom HUD)
        val sw = sceneBitmap.width
        val sh = sceneBitmap.height
        val targetRatio = targetPhotoWidth / targetPhotoHeight
        val srcRatio = sw.toFloat() / sh.toFloat()

        val srcRect = if (srcRatio > targetRatio) {
            val cropW = (sh * targetRatio).toInt().coerceAtMost(sw)
            val srcX = (sw - cropW) / 2
            Rect(srcX, 0, srcX + cropW, sh)
        } else {
            val cropH = (sw / targetRatio).toInt().coerceAtMost(sh)
            val srcY = ((sh - cropH) * 0.48f).toInt().coerceIn(0, (sh - cropH).coerceAtLeast(0))
            Rect(0, srcY, sw, srcY + cropH)
        }

        val dstRect = RectF(photoLeft, photoTop, photoRight, photoBottom)
        val photoPaint = Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG)
        canvas.drawBitmap(sceneBitmap, srcRect, dstRect, photoPaint)

        // Inner photo frame border (subtle 1.5px bevel)
        val photoBorderPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#DDD7CE")
            style = Paint.Style.STROKE
            strokeWidth = 2f
        }
        canvas.drawRect(photoLeft, photoTop, photoRight, photoBottom, photoBorderPaint)

        // 3. Caption Area (y = 1040 to 1440)
        // Autogenerated Title — Bold serif typeface
        val titlePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#1E293B")
            typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            textAlign = Paint.Align.CENTER
            textSize = 48f
        }
        // Auto-scale title down if it's too long
        while (titlePaint.measureText(title) > (cardWidth - 140f) && titlePaint.textSize > 30f) {
            titlePaint.textSize -= 2f
        }
        canvas.drawText(title, cardWidth / 2f, 1145f, titlePaint)

        // Scene Name & Date Line — Soft serif
        val datePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#64748B")
            typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
            textSize = 28f
        }
        val dateText = if (sceneName.isNotBlank() && date.isNotBlank()) {
            "$sceneName  •  $date"
        } else {
            sceneName.ifBlank { date }
        }
        canvas.drawText(dateText, cardWidth / 2f, 1215f, datePaint)

        // Timestamp Line — Clean monospace
        if (time.isNotBlank()) {
            val timePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
                color = AndroidColor.parseColor("#94A3B8")
                typeface = Typeface.MONOSPACE
                textAlign = Paint.Align.CENTER
                textSize = 22f
            }
            canvas.drawText(time, cardWidth / 2f, 1270f, timePaint)
        }

        // Tiny Us cozy brand mark at the bottom
        val brandPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#E5989B")
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
            textAlign = Paint.Align.CENTER
            textSize = 20f
            letterSpacing = 0.14f
        }
        canvas.drawText("♥  T I N Y   U S", cardWidth / 2f, 1370f, brandPaint)

        // Outer card border
        val cardBorderPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = AndroidColor.parseColor("#E8E2D8")
            style = Paint.Style.STROKE
            strokeWidth = 2f
        }
        canvas.drawRoundRect(
            RectF(1f, 1f, cardWidth - 1f, cardHeight - 1f),
            cornerRadius,
            cornerRadius,
            cardBorderPaint
        )

        return cardBitmap
    }

    /**
     * Saves the complete Polaroid card [bitmap] into the device's public Pictures/Tiny Us gallery.
     * Accessible immediately from Google Photos and Device Gallery.
     * Returns true on success, false on error.
     */
    fun saveToDeviceGallery(bitmap: Bitmap, title: String): Boolean {
        return runCatching {
            val cleanTitle = title.replace(Regex("[^a-zA-Z0-9]"), "_").take(20)
            val filename = "TinyUs_${cleanTitle}_${System.currentTimeMillis()}.png"
            val resolver = context.contentResolver

            val values = ContentValues().apply {
                put(MediaStore.Images.Media.DISPLAY_NAME, filename)
                put(MediaStore.Images.Media.MIME_TYPE, "image/png")
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    put(MediaStore.Images.Media.RELATIVE_PATH, Environment.DIRECTORY_PICTURES + File.separator + "Tiny Us")
                    put(MediaStore.Images.Media.IS_PENDING, 1)
                }
            }

            val uri = resolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values)
                ?: return false

            resolver.openOutputStream(uri)?.use { out ->
                bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
            } ?: return false

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                values.clear()
                values.put(MediaStore.Images.Media.IS_PENDING, 0)
                resolver.update(uri, values, null, null)
            }
            true
        }.getOrDefault(false)
    }

    /**
     * Deletes the image file at [path]. No-op if already absent.
     */
    fun deleteImage(path: String) {
        File(path).takeIf { it.exists() }?.delete()
    }

    // ─── Metadata Persistence ─────────────────────────────────────────────────

    fun getPolaroids(): List<PolaroidMemory> {
        val raw = prefs.getString("polaroids_json", null) ?: return emptyList()
        return runCatching {
            val arr = JSONArray(raw)
            (0 until arr.length()).map { i ->
                val obj = arr.getJSONObject(i)
                PolaroidMemory(
                    id = obj.optString("id", UUID.randomUUID().toString()),
                    title = obj.optString("title", "Tiny Moment"),
                    date = obj.optString("date", ""),
                    time = obj.optString("time", ""),
                    sceneName = obj.optString("sceneName", ""),
                    sceneEnvKey = obj.optString("sceneEnvKey", ""),
                    imagePath = obj.optString("imagePath", "")
                )
            }.reversed() // newest first
        }.getOrDefault(emptyList())
    }

    fun savePolaroid(memory: PolaroidMemory) {
        val current = getPolaroids().toMutableList()
        // Insert newest at front; keep at most 60
        current.add(0, memory)
        val trimmed = current.take(60)
        val arr = JSONArray()
        trimmed.reversed().forEach { m ->          // store oldest-first so reversed() above works
            arr.put(JSONObject().apply {
                put("id", m.id)
                put("title", m.title)
                put("date", m.date)
                put("time", m.time)
                put("sceneName", m.sceneName)
                put("sceneEnvKey", m.sceneEnvKey)
                put("imagePath", m.imagePath)
            })
        }
        prefs.edit().putString("polaroids_json", arr.toString()).apply()
    }

    fun deletePolaroid(id: String) {
        val current = getPolaroids().toMutableList()
        val target = current.firstOrNull { it.id == id } ?: return
        deleteImage(target.imagePath)
        current.removeAll { it.id == id }
        // Re-serialize
        val arr = JSONArray()
        current.reversed().forEach { m ->
            arr.put(JSONObject().apply {
                put("id", m.id)
                put("title", m.title)
                put("date", m.date)
                put("time", m.time)
                put("sceneName", m.sceneName)
                put("sceneEnvKey", m.sceneEnvKey)
                put("imagePath", m.imagePath)
            })
        }
        prefs.edit().putString("polaroids_json", arr.toString()).apply()
    }

    // ─── Title Generation ─────────────────────────────────────────────────────

    /**
     * Picks a cozy title for the captured moment. Biased toward scene-specific
     * and time-appropriate titles when available, cycling through to avoid repetition.
     */
    fun pickTitle(sceneEnvKey: String, isNight: Boolean = false, isSunset: Boolean = false): String {
        val sceneTitles = SCENE_TITLES[sceneEnvKey]
        val timeTitles = when {
            isNight -> TIME_TITLES_NIGHT
            isSunset -> TIME_TITLES_SUNSET
            else -> TIME_TITLES_DAY
        }
        val universal = UNIVERSAL_TITLES

        // Build weighted pool: scene-specific x3, time-aware x2, universal x1
        val pool = mutableListOf<String>()
        sceneTitles?.let { pool.addAll(it); pool.addAll(it); pool.addAll(it) }
        timeTitles.let { pool.addAll(it); pool.addAll(it) }
        pool.addAll(universal)

        // Anti-repeat: exclude last 20 used titles to keep fresh
        val usedRaw = prefs.getString("used_titles", "") ?: ""
        val used = if (usedRaw.isBlank()) emptyList() else usedRaw.split("|")
        val candidates = pool.filter { it !in used }.ifEmpty { pool }

        val picked = candidates.random()

        // Persist last 20 used
        val newUsed = (used + picked).takeLast(20).joinToString("|")
        prefs.edit().putString("used_titles", newUsed).apply()

        return picked
    }

    // ─── Timestamp helpers ────────────────────────────────────────────────────

    fun formattedDate(): String =
        SimpleDateFormat("MMM d, yyyy", Locale.getDefault()).format(Date())

    fun formattedTime(): String =
        SimpleDateFormat("h:mm a", Locale.getDefault()).format(Date())

    // ─── Title Pools ─────────────────────────────────────────────────────────

    companion object {
        /** Scene-specific titles keyed by EnvironmentType name */
        val SCENE_TITLES: Map<String, List<String>> = mapOf(
            "MEADOW" to listOf(
                "Wildflower Days", "Petals and You", "Soft Afternoon",
                "Fields We Know", "Bloom Beside Me", "A Flower For You",
                "Gentle Meadow Hours", "Where Buttercups Grow", "Sun-Dappled Grass",
                "Breeze in the Clover", "Fresh Cut Stems", "Picnic in the Sun"
            ),
            "TREE_HILL" to listOf(
                "Shade and Quiet", "Under Our Tree", "Beneath the Branches",
                "Cool Green Afternoon", "The Old Tree Knows", "Roots and Us",
                "Whispers Under Leaves", "Canopy Hours", "Leaning on the Bark",
                "Watching Clouds Drift", "Our Secret Hilltop", "Green Leaves, Soft Heart"
            ),
            "KITCHEN" to listOf(
                "Secret Ingredient", "Warm From the Stove", "Kitchen Thief",
                "Stolen Bites", "Something's Cooking", "Our Little Recipe",
                "Saturday Morning Smells", "Apron Hours", "Taste Testing",
                "Flour on Your Nose", "Warm Cinnamon Air", "Simmering Slowly"
            ),
            "LIVING_ROOM" to listOf(
                "Couch Cuddle", "Slow Evenings", "Quietly Together",
                "Blanket Weather", "Soft Lamplight", "Sofa Stories",
                "Cozy Inside", "Not Going Anywhere", "Warm Feet, Warm Soul",
                "Lazy Living Room", "Reading by Candlelight", "Curled Up Tight"
            ),
            "PATH_NIGHT" to listOf(
                "Under the Same Sky", "Lantern Glow", "Night Stroll",
                "Stars Know Us", "Side by Side", "Moonlit Walk",
                "The Long Way Home", "Late Evening Light", "Pagoda Shadows",
                "Hand in Hand", "Lavender on the Breeze", "Footsteps in the Quiet"
            ),
            "TWILIGHT" to listOf(
                "Just Looking at You", "Golden Hour Pause", "Dusk and Us",
                "Soft Goodbye to the Day", "Pink Sky Moment", "Twilight Quiet",
                "Last Light Together", "Before the Stars", "Amber Horizon",
                "Softest Gazes", "The Sky Painted Pink", "Evening Sigh"
            ),
            "MOMO_STALL" to listOf(
                "Warm Dumplings Night", "Hot Dumplings Happiness", "Our Favorite Spot",
                "Chili and Laughter", "Street Food Love", "Steam and Smiles",
                "The Best Table", "Friday Night Craving", "Extra Spicy Bites",
                "Bamboo Steamer Steam", "Our Corner Stall", "Stealing Dumplings"
            ),
            "EVENING_ROAD" to listOf(
                "Scooter Rides", "Evening Breeze", "Hold On Tight",
                "Wind in Your Hair", "Riding Together", "Cozy Evenings",
                "Streets We Rode", "Fast and Us", "Two Helmets, One Way",
                "Scooter Hum", "Passing City Lights", "Through the Warm City"
            ),
            "COZY_LOFT" to listOf(
                "Midnight Vinyl", "City Glow Cuddle", "Tea and You",
                "Loft Dreaming", "High Above the World", "Blanket and Music",
                "City Lights and Us", "Slow Midnight", "Needle on the Groove",
                "Steam from the Mug", "Rooftop Calm", "Our Little Sanctuary"
            )
        )

        /** Time-of-day specific pools */
        val TIME_TITLES_NIGHT: List<String> = listOf(
            "Under the Moonlight", "Curled Up at Midnight", "Counting Stars",
            "Whispering in the Dark", "While The City Sleeps", "Midnight Blue",
            "Quiet Night In", "Sleeping beside You", "Starlight Over Us",
            "Late Night Softness", "Nightfall Sanctuary", "Dim Lamps and Us"
        )

        val TIME_TITLES_SUNSET: List<String> = listOf(
            "Golden Hour Magic", "Sunset Glow", "When the Day Dims",
            "Warm Amber Skies", "Watching the Day Fade", "Evening Falling",
            "Soft Peach Sky", "Dusk Beside You", "Sun Sinking Low"
        )

        val TIME_TITLES_DAY: List<String> = listOf(
            "Morning Sun on Us", "Gentle Daylight", "Bright and Sweet",
            "Lazy Sunday Morning", "Sunbeams on the Floor", "Clear Skies Ahead",
            "Basking in Daylight", "Small Morning Joy", "A Fresh Little Day"
        )

        /** Universal titles usable in any scene */
        val UNIVERSAL_TITLES: List<String> = listOf(
            "Just Us",
            "A Little Moment",
            "Our Little World",
            "Little Things",
            "Stay A Little Longer",
            "Home With You",
            "A Place for Two",
            "Quietly Yours",
            "Soft and Warm",
            "Right Here",
            "No Rush",
            "Us Again",
            "Two of Us",
            "This Exact Moment",
            "Slow Sunday",
            "Always This",
            "Our Tiny Life",
            "Near You",
            "Gentle Afternoon",
            "Safe and Warm",
            "The Sweetest Thing",
            "While The World Slept",
            "Somewhere Cozy",
            "Another Day With You",
            "Small and Perfect",
            "This Is Enough",
            "A Quiet Kind of Happy",
            "Made For This",
            "Unhurried",
            "Tucked In Together",
            "Still Here",
            "Wherever You Are",
            "Our Corner",
            "Warmly",
            "Not Wanting to Leave",
            "Let's Stay",
            "The Best Part",
            "Always the Best Day",
            "Just the Two of Us",
            "A Memory Already",
            "Treasured Forever",
            "My Favorite View",
            "Everyday Magic",
            "Peaceful Hours",
            "Where I Belong",
            "Pure Comfort",
            "Just Like This",
            "Cherished Hour",
            "Forever Small",
            "With You, Always"
        )
    }
}
